---
- name: Install nginx
  apt:
    name: 
      - nginx
      - certbot
      - python3-certbot-nginx
    state: latest
    update_cache: yes
- name: Open ufw firewall
  shell: "ufw delete allow 'Nginx HTTP' && ufw allow 'Nginx Full'"
- name: Create www directory
  file:
    path: /var/www/{{ domain_name }}
    state: directory
    # must be root:root 0755 for sftp chroot to work
    owner: root
    group: root
    mode: '0755'
- name: delete default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx
- name: Copy nginx global conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
- name: Copy nginx site conf
  template:
    src: site.conf.j2
    dest: /etc/nginx/sites-enabled/{{ domain_name }}
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx
- name: Initial letsencrypt setup
  command:
    cmd: "certbot certonly --non-interactive --webroot -w /var/www/{{ domain_name}} --agree-tos -m {{ letsencrypt_mail  }} -d {{ domain_name }} --rsa-key-size 4096"
  notify: restart nginx
- name: Configure logrotate for nginx
  template:
    src: nginx-logrotate.j2
    dest: /etc/logrotate.d/nginx
  vars:
    access_rotate_days: 1
    error_rotate_days: 7



