---
- name: Install nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes
- name: Open ufw firewall
  command:
    cmd: "ufw allow 'Nginx HTTP'"
- name: Create www directory
  file:
    path: /var/www/{{ domain_name }}
    state: directory
    mode: '0775'
- name: delete default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx
- name: Copy nginx site conf
  template:
    src: site.conf.j2
    dest: /etc/nginx/sites-enabled/{{ domain_name }}
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx


