---
- name: Install unattended-upgrades
  apt:
    name:
      - unattended-upgrades
    state: present
- name: Configure unattended-upgrades
  command:
    cmd: echo unattended-upgrades unattended-upgrades/enable_auto_updates boolean true | debconf-set-selections && dpkg-reconfigure -f noninteractive unattended-upgrades


