---
- name: Install ufw
  apt:
    name: ufw
    state: latest
    update_cache: yes
- name: Allow ssh access through ufw
  command:
    cmd: ufw allow OpenSSH
- name: Enable ufw
  command:
    cmd: ufw --force enable

  
